---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: User sign in
      tags:
      - Users
      consumes:
      - application/json
      - application/xml
      parameters:
      - auth: user
        email: user
        password: user
        in: body
        schema:
          type: object
          properties:
            auth:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          required:
          - auth
          - email
          - password
      responses:
        '201':
          description: token created
        '422':
          description: invalid request
  "/api/v1/me":
    post:
      summary: User info
      tags:
      - Users
      consumes:
      - application/json
      - application/xml
      parameters:
      - email: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
          required:
          - email
      responses:
        '200':
          description: users info returned
        '422':
          description: invalid request
